name: Update README
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Update README with recent GitHub activity
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: "⚡ Update README with the recent activity" 
          MAX_LINES: 5
          COMMIT_NAME: "GitHub Activity Readme"
          TARGET_FILE: "README.md"
