name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Atualizar Readme com Métricas
    runs-on: ubuntu-24.04  # Updated to use Ubuntu 24.04
    
    steps:
      - name: Obter dados de WakaTime e atualizar o README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
                    
          SHOW_OS: "False"           
          SHOW_PROJECTS: "False"     
          SHOW_DAYS_OF_WEEK: "False" 
          SHOW_LANGUAGE: "True"     
          SHOW_TIMEZONE: "True"    
          SHOW_EDITORS: "True"
